version: '3'

services:
  nginx:
    container_name: star-wars-nginx
    image: nginx:1.15-alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/app:delegated
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  redis:
    container_name: star-wars-redis
    image: redis:alpine
    ports:
      - 6380:6379

  node:
    container_name: star-wars-node
    build:
      context: .
      dockerfile: ./etc/node/Dockerfile
    volumes:
      - .:/app:delegated
    working_dir: /app
    depends_on:
      - php

  php:
    container_name: star-wars-php
    build:
      context: .
      dockerfile: ./etc/php/Dockerfile
    restart: unless-stopped
    ports:
      - "9090:9001"
    volumes:
      - .:/app:delegated
    env_file:
      - .env