parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    StarWars\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    StarWars\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    GuzzleHttp\ClientInterface:
        alias: GuzzleHttp\Client

    GuzzleHttp\Client:
        class: GuzzleHttp\Client
        arguments:
            - handler: '@http_client.handlerstack'
              connect_timeout: 5
              timeout: 5

    http_client.handlerstack:
        class: GuzzleHttp\HandlerStack
        factory: [GuzzleHttp\HandlerStack, 'create']
        calls:
            - ['push', ['@http_client.middleware.closure', 'predis_cache']]

    http_client.middleware.closure:
        class: Closure
        factory:
            - 'StarWars\Service\Middleware\CachedMiddleware'
            - 'onRequest'
        arguments:
            - '@redis_cache'
            - '%env(REDIS_TTL)%'

    redis_cache:
        class: StarWars\Service\RedisCache
        arguments:
            - '@redis_client'

    redis_client:
        class: Closure
        factory:
            - 'Symfony\Component\Cache\Adapter\RedisAdapter'
            - 'createConnection'
        arguments:
            - '%env(REDIS_CONNECTION)%'
            - class: \Redis

    cache_adapter:
        class: Symfony\Component\Cache\Adapter\RedisAdapter
        arguments:
            - '@redis_client'

    StarWars\Service\Normalizer\:
        resource: '../src/Service/Normalizer/*'
        tags:
            - 'serializer.normalizer'
            - 'serializer.denormalizer'